-- Histórico de itens que passaram pelo status pago (permite relatório mensal incremental mesmo após exclusão)
CREATE TABLE IF NOT EXISTS demanda_itens_historico_pago (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  obra_id BIGINT NOT NULL REFERENCES obras(id) ON DELETE CASCADE,
  demanda_item_id BIGINT,
  titulo TEXT NOT NULL,
  categoria TEXT,
  descricao TEXT,
  valor DECIMAL(10,2),
  data_pedido TIMESTAMP WITH TIME ZONE,
  data_entrega TIMESTAMP WITH TIME ZONE,
  data_pagamento TIMESTAMP WITH TIME ZONE,
  tempo_entrega TEXT,
  observacao_entrega TEXT,
  nota_fiscal TEXT[],
  origem TEXT NOT NULL DEFAULT 'movido_para_pago',
  entrou_em_pago_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE demanda_itens_historico_pago
  ADD COLUMN IF NOT EXISTS categoria TEXT;

-- Evita duplicar histórico da mesma entrada em pago para o mesmo item
CREATE UNIQUE INDEX IF NOT EXISTS idx_demanda_historico_item_data_pagamento
  ON demanda_itens_historico_pago (demanda_item_id, data_pagamento);

CREATE INDEX IF NOT EXISTS idx_demanda_historico_obra
  ON demanda_itens_historico_pago (obra_id);

CREATE INDEX IF NOT EXISTS idx_demanda_historico_pago_em
  ON demanda_itens_historico_pago (entrou_em_pago_em);

ALTER TABLE demanda_itens_historico_pago ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Usuários podem ver histórico de demanda" ON demanda_itens_historico_pago;
CREATE POLICY "Usuários podem ver histórico de demanda"
  ON demanda_itens_historico_pago FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Usuários podem inserir histórico de demanda" ON demanda_itens_historico_pago;
CREATE POLICY "Usuários podem inserir histórico de demanda"
  ON demanda_itens_historico_pago FOR INSERT
  TO authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Usuários podem atualizar histórico de demanda" ON demanda_itens_historico_pago;
CREATE POLICY "Usuários podem atualizar histórico de demanda"
  ON demanda_itens_historico_pago FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Usuários podem excluir histórico de demanda" ON demanda_itens_historico_pago;
CREATE POLICY "Usuários podem excluir histórico de demanda"
  ON demanda_itens_historico_pago FOR DELETE
  TO authenticated
  USING (true);
